### PR TITLE
Complete rewrite of the laser code

### PR DESCRIPTION
**Pull request by orcinus**
The laser code has been completely rewritten to calculate actual microns between pulses (based on steps and step lengths) and to use the ISR timer to calculate pulse length (in ms).

The code's massively better optimized compared to the original one and does not cause any stepper hiccups anymore. In fact, it's completely smooth and can now endure higher accelerations and handle steppers wired in series just fine (axis binding was in part due to badly optimized old code).

Pulse firing is now much more accurate as well and pulse lengths are completely jitter free and regular. The odd pulse bugs and flashes are gone too.

NOTE: the slower the speed, the lower the precision of the pulse lengths - the minimum pulse length is limited by the length of one ISR cycle, which depends on the stepper speed. That means that, for example, at 100 mm/min you will get a precision of cca. 16ms, i.e. the minimum pulse length becomes 16ms and valid pulse lengths are 16000, 32000, 47000 etc. At normal speeds (above 1200 mm/min or so) this effect is negligible. I'm mentioning it here as a testing note.

### CODE REVIEW

**Comment by orcinus** [comment]
I left in a bug by accident that's probably causing the laser output power to be lower than normal.
Please don't test with an actual print as it will likely cause severe undercure even at 100% power.

Fix coming soon.

**Comment by orcinus** [comment]
Bug fixed, a few M commands changed/added. M7 now fires the laser indefinitely or until the next move (unlike M6), while M8 shuts it off. Useful for testing, focusing etc.

M7 accepts an optional S parameter for laser intensity (e.g. M7 S50).

I'm considering adding support for different first layer laser settings via a new M command.
The idea would be that you issue the laser settings for the first layer using that and then via M649 for all the following layers (as it is now). The first setting would then be in effect until the first peel move, at which point the "normal" settings would get loaded.

**Comment by orcinus** [comment]
I might have found a bug in the code, not sure how to replicate yet. It's not destructive and it doesn't impair the quality too much.

Basically, sometimes (random) the laser turns on during the lowering move of a peel. This causes a single spot to overcure, which isn't that bad, because it's just a tiny sliver of extra cured resin at random places that falls off during rinsing.

I'm not sure yet if it's actually caused by the new code or by the gcode, as i've been testing KISSlicer for use with mUVe (verdict: less practical than Slic3r, because of the way it handles custom gcode) and it does odd things on layer changes (e.g. it does Z moves to the next layer combined with the move to layer start coordinates, instead of in a separate move).

**Comment by orcinus** [comment]
Fixed the laser firing during a peel bug.
Fixed laser staying on when print from SD is paused/stopped (until the next move).
Cleaned up some stuff.
Removed raster support.

**Comment by mUVe3D** [comment]
Clean coding, we can't thank you enough! Time to pull it in for testing :)

**Pull request merged**
